config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  get 'questions/index'
  get 'questions/show'
  get 'questions/new'
  get 'questions/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, only: %i[create edit destroy update] do
      collection do
      get 'answer'
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, :title, :keyword, presence: true
  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def own?(object)
    id == object.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :require_login, only: %i[create edit update destroy]
    before_action :set_answer, only: %i[edit update destroy]

    def create
        @answer = current_user.answers.build(answer_params)
        #questionのkeywordを配列にする。
        keywords = Question.find(params[:question_id]).keyword.split(',')
        #配列の要素がそれぞれanswerのbodyに含まれているかを検証する
        count = 0
        @forgotten_words = Array.new
        keywords.each do |keyword|
        if @answer.body.include? "#{keyword}"
            count += 1
        else
            @forgotten_words.push(keyword)
        end
        end
        #正答率をインスタンス変数に渡す
        @answer.forgotten_words = @forgotten_words
        @answer.correct_rate = count/keywords.count.to_f * 100
        if @answer.save
          redirect_to answer_question_answers_path, success: '回答しました'
        else
          redirect_to question_path(answer.question), success: '回答できませんでした'
        end
    end

    def edit
      @question = Question.find(@answer.question.id)
    end

    def update
        @answer.update(answer_update_params)
        redirect_to question_path(@answer.question)
    end

    def destroy
        @answer.destroy!
        redirect_to question_path(@answer.question)
    end

    def answer
      @question = Question.find(params[:question_id])
      @answers = @question.answers.includes(:user).order(created_at: :desc)
    end

    private
    def set_answer
      @answer = current_user.answers.find(params[:id])
    end

    def answer_params
        params.require(:answer).permit(:body).merge(question_id: params[:question_id])
    end

    def answer_update_params
        params.require(:answer).permit(:body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  def not_authenticated
  	redirect_to login_path, warning: 'ログインしてください'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :set_question, only: [:show, :edit, :update, :destroy]
before_action :require_login, only: %i[new create edit update destroy]
  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to questions_path, success: '質問を作成しました'
    else
      flash.now[:danger] = '失敗しました'
      render :new
    end
  end


  def edit ;end

  def update
	if @question.update(question_params)
		redirect_to question_path(@question), success: '質問を更新しました'
	else
		flash.now[:danger] = '失敗しました'
		render :edit
	end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

private

  def question_params
    params.require(:question).permit(:title, :body, :hint, :keyword, :correct_answer)
  end
  def set_question
  	@question = current_user.questions.find(params[:id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<div class="container">
  <tr class="border">
    <td>
      <h5><%= answer.user.name %></h5>
      <h5>スコア：<%= answer.correct_rate %>/100点</h5>
      <h5>次のワードが抜けています<%= answer.forgotten_words %></h5>
      <div class="container mt-3">
        <%= simple_format(answer.body)%>
      </div>
    </td>
  
    <% if current_user.own?(answer) %>
      <td class="action">
        <ul class="list-inline justify-content-center" style="float: right;">
          <li class="list-inline-item">
            <%= link_to edit_question_answer_path(answer.question, answer) do %>
              <p>編集</p>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to question_answer_path(answer.question, answer), method: :delete, data: { confirm: '本当に削除しますか？' } do %>
              <p>削除</p>
            <% end %>
          </li>
        </ul>
      </td>
    <% end %>
  </tr>
<div>

app/views/answers/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: answer, url: [question, answer], local: true do |f| %>
    <div class="form-group pb-3">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', rows: 5, placeholder: '回答を記述してください'%>
     </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/answers/answer.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
    <%= link_to '問題ページに移動', question_path(@question) %>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-12 pb-3'>
              <h4 class='border-bottom'>タイトル</h4>
              <h5 class="d-inline"><%= @question.title %></h5>
            </div>
            <div class='col-md-12 pb-3'>
              <h4 class='border-bottom'>問題文</h4>
              <h5 class="d-inline"><%= simple_format(@question.body) %></h5>
            </div>
            <div class='col-md-12 pb-3'>
              <h4 class='border-bottom'>模範回答</h4>
              <h5 class="d-inline"><%= simple_format(@question.correct_answer) %></h5>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="row">
  <div class="col-lg-8 offset-lg-2 ">
    <table class="table">
      <%= render partial: "answer", collection: @answers%>
    </table>
  </div>
</div>
</div>

app/views/answers/edit.html.erb
<div class="container">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
      <%= render 'form', { question: @question, answer: @answer } %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MacroMemory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/questions/_crud.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_question_path(question), id: "button-edit-#{question.id}" do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to question_path(question), method: :delete, data: { confirm: '本当に削除しますか？' }, id: "button-delete-#{question.id}" do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </li>
</ul>

app/views/questions/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_question_path(question), id: "button-edit-#{question.id}" do %>
      <p>編集</p>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to question_path(question), method: :delete, data: { confirm: '本当に削除しますか？' }, id: "button-delete-#{question.id}" do %>
      <p>削除</p>
    <% end %>
  </li>
</ul>

app/views/questions/_form.html.erb
<%= form_with model: question, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 5%>
  </div>
  <div class="form-group">
    <%= f.label :hint %>
    <%= f.text_area :hint, class: 'form-control', rows: 2 %>
  </div>
  <div class="form-group">
    <%= f.label :correct_answer %>
    <%= f.text_area :correct_answer, class: 'form-control', rows: 8%>
  </div>
  <div class="form-group">
    <%= f.label :keyword %>
    <%= f.text_area :keyword, class: 'form-control'%>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="question-id-<%= question.id %>">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to question.title, question_path(question) %>
          <%= render 'crud_menus', question: question %>
        </h4>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= question.created_at %>
          </li>
        </ul>
        <p class="card-text"><%= question.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
      <%= render 'form', { question: @question } %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="row pt-3 px-4">
    <div class="col-12">
      <div class="row">
        <% if @questions.present? %>
          <%= render @questions %>
        <% else %>
          <p>投稿はありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
      <%= render 'form', { question: @question } %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
    <%= link_to '解答ページに移動', answer_question_answers_path(@question)%>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-9'>
              <h4 class="d-inline"><%= @question.title %></h4>
              <%= render 'crud_menus', question: @question %>
            </div>
          </div>
          <h5><%= simple_format(@question.body) %></h5>
        </div>
      </article>
    </div>
  </div>
  <%= render 'answers/form', { question: @question, answer: @answer } %>
</div>

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'マクロ暗記', questions_path, class: "navbar-brand"%>
    <div class="ms-auto">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav text-end ">
          <li class="nav-item px-3">
                <li><%= link_to 'ログイン', login_path, class: 'dropdown-item' %></li>
              </ul>
            </div>
          </li>
        </ul>
    </div>
    </div>
  </div>
</nav>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
        <div class='copyright text-center'>
          <p>Copyright © 2022 Inc. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'マクロ暗記', questions_path, class: "navbar-brand"%>
    <div class="ms-auto">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav text-end ">
          <li class="nav-item ">
            <%= link_to '投稿する', new_question_path, class: 'nav-link' %>
          </li>
          <li class="nav-item px-3">
                <li><%= link_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %></li>
              </ul>
            </div>
          </li>
        </ul>
    </div>
    </div>
  </div>
</nav>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ログイン</h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit 'ログイン', class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to '登録ページへ', new_user_path %>
        <a href="#">パスワードをお忘れの方はこちら</a>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>